using Xui.GPU.Backends.Hlsl;
using Xui.GPU.Backends.Metal;
using Xui.GPU.IR;

namespace Xui.GPU.Generator.Emission;

/// <summary>
/// Emits the Generated.cs partial struct with pre-compiled shader source strings.
/// </summary>
internal static class ShaderSourceEmitter
{
    public static string Emit(string ns, string typeName, IrShaderModule module)
    {
        var hlsl = new HlslCodeGenerator().GenerateCode(module);
        var msl = new MslCodeGenerator().GenerateCode(module);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by Xui.GPU.Generator from [ShaderProgram] type.");
        sb.AppendLine();
        sb.AppendLine("using Xui.GPU.Backends;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(ns))
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }

        sb.AppendLine($"partial struct {typeName}");
        sb.AppendLine("{");

        // Entry point constants
        sb.AppendLine("    public const string HlslVertexEntry = \"VSMain\";");
        sb.AppendLine("    public const string HlslFragmentEntry = \"PSMain\";");
        sb.AppendLine("    public const string MslVertexEntry = \"vertex_main\";");
        sb.AppendLine("    public const string MslFragmentEntry = \"fragment_main\";");
        sb.AppendLine();

        // GetVertexEntry
        sb.AppendLine("    public static string GetVertexEntry(string backendName) => backendName switch");
        sb.AppendLine("    {");
        sb.AppendLine("        \"HLSL\" => HlslVertexEntry,");
        sb.AppendLine("        \"MSL\" => MslVertexEntry,");
        sb.AppendLine("        _ => throw new System.NotSupportedException($\"Unknown shader backend: {backendName}\")");
        sb.AppendLine("    };");
        sb.AppendLine();

        // GetFragmentEntry
        sb.AppendLine("    public static string GetFragmentEntry(string backendName) => backendName switch");
        sb.AppendLine("    {");
        sb.AppendLine("        \"HLSL\" => HlslFragmentEntry,");
        sb.AppendLine("        \"MSL\" => MslFragmentEntry,");
        sb.AppendLine("        _ => throw new System.NotSupportedException($\"Unknown shader backend: {backendName}\")");
        sb.AppendLine("    };");
        sb.AppendLine();

        // Embedded shader sources
        sb.AppendLine($"    private const string HlslSource = @\"{EscapeVerbatim(hlsl)}\";");
        sb.AppendLine();
        sb.AppendLine($"    private const string MslSource = @\"{EscapeVerbatim(msl)}\";");
        sb.AppendLine();

        // GenerateShaderSource
        sb.AppendLine("    public static string GenerateShaderSource(IShaderBackend backend) => backend.Name switch");
        sb.AppendLine("    {");
        sb.AppendLine("        \"HLSL\" => HlslSource,");
        sb.AppendLine("        \"MSL\" => MslSource,");
        sb.AppendLine("        _ => throw new System.NotSupportedException($\"Unknown shader backend: {backend.Name}\")");
        sb.AppendLine("    };");

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string EscapeVerbatim(string s) => s.Replace("\"", "\"\"");
}
