namespace Xui.Core.Canvas;

/// <summary>
/// Provides web standard named color constants in 32-bit RGBA format (0xRRGGBBAA).
/// These match the named colors from the CSS color specification:
/// https://developer.mozilla.org/en-US/docs/Web/CSS/named-color
/// </summary>
public static class Colors
{
#pragma warning disable CS1591
    public const uint Transparent = 0x00000000;

    public const uint Black = 0x000000FF;
    public const uint White = 0xFFFFFFFF;

    public const uint Red = 0xFF0000FF;
    public const uint Lime = 0x00FF00FF;
    public const uint Blue = 0x0000FFFF;

    public const uint Yellow = 0xFFFF00FF;
    public const uint Fuchsia = 0xFF00FFFF;
    public const uint Aqua = 0x00FFFFFF;

    public const uint Silver = 0xC0C0C0FF;
    public const uint Gray = 0x808080FF;
    public const uint Maroon = 0x800000FF;
    public const uint Purple = 0x800080FF;
    public const uint Green = 0x008000FF;
    public const uint Olive = 0x808000FF;
    public const uint Navy = 0x000080FF;
    public const uint Teal = 0x008080FF;

    public const uint AliceBlue = 0xf0f8ffFF;
    public const uint AntiqueWhite = 0xfaebd7FF;
    public const uint Aquamarine = 0x7fffd4FF;
    public const uint Azure = 0xf0ffffFF;
    public const uint Beige = 0xf5f5dcFF;
    public const uint Bisque = 0xffe4c4FF;
    public const uint BlanchedAlmond = 0xffebcdFF;
    public const uint BlueViolet = 0x8a2be2FF;
    public const uint Brown = 0xa52a2aFF;
    public const uint BurlyWood = 0xdeb887FF;
    public const uint CadetBlue = 0x5f9ea0FF;
    public const uint ChartReuse = 0x7fff00FF;
    public const uint Chocolate = 0xd2691eFF;
    public const uint Coral = 0xff7f50FF;
    public const uint CornflowerBlue = 0x6495edFF;
    public const uint CornSilk = 0xfff8dcFF;
    public const uint Crimson = 0xdc143cFF;
    public const uint Cyan = 0x00ffffFF;
    public const uint DarkBlue = 0x00008bFF;
    public const uint DarkCyan = 0x008b8bFF;
    public const uint DarkGoldenRod = 0xb8860bFF;
    public const uint DarkGray = 0xa9a9a9FF;
    public const uint DarkGreen = 0x006400FF;
    public const uint DarkGrey = 0xa9a9a9FF;
    public const uint DarkKhaki = 0xbdb76bFF;
    public const uint DarkMagenta = 0x8b008bFF;
    public const uint DarkOliveGreen = 0x556b2fFF;
    public const uint DarkOrange = 0xff8c00FF;
    public const uint DarkOrchid = 0x9932ccFF;
    public const uint DarkRed = 0x8b0000FF;
    public const uint DarkSalmon = 0xe9967aFF;
    public const uint DarkSeaGreen = 0x8fbc8fFF;
    public const uint DarkSlateBlue = 0x483d8bFF;
    public const uint DarkSlateGray = 0x2f4f4fFF;
    public const uint DarkSlateGrey = 0x2f4f4fFF;
    public const uint DarkTurquoise = 0x00ced1FF;
    public const uint DarkViolet = 0x9400d3FF;
    public const uint DeepPink = 0xff1493FF;
    public const uint DeepSkyBlue = 0x00bfffFF;
    public const uint DimGray = 0x696969FF;
    public const uint DimGrey = 0x696969FF;
    public const uint DodgerBlue = 0x1e90ffFF;
    public const uint FireBrick = 0xb22222FF;
    public const uint FloralWhite = 0xfffaf0FF;
    public const uint ForestGreen = 0x228b22FF;
    public const uint Gainsboro = 0xdcdcdcFF;
    public const uint GhostWhite = 0xf8f8ffFF;
    public const uint Gold = 0xffd700FF;
    public const uint GoldenRod = 0xdaa520FF;
    public const uint GreenYellow = 0xadff2fFF;
    public const uint Grey = 0x808080FF;
    public const uint Honeydew = 0xf0fff0FF;
    public const uint HotPink = 0xff69b4FF;
    public const uint IndianRed = 0xcd5c5cFF;
    public const uint Indigo = 0x4b0082FF;
    public const uint Ivory = 0xfffff0FF;
    public const uint Khaki = 0xf0e68cFF;
    public const uint Lavender = 0xe6e6faFF;
    public const uint LavenderBlush = 0xfff0f5FF;
    public const uint LawnGreen = 0x7cfc00FF;
    public const uint LemonChiffon = 0xfffacdFF;
    public const uint LightBlue = 0xadd8e6FF;
    public const uint LightCoral = 0xf08080FF;
    public const uint LightCyan = 0xe0ffffFF;
    public const uint LightGoldenRodYellow = 0xfafad2FF;
    public const uint LightGray = 0xd3d3d3FF;
    public const uint LightGreen = 0x90ee90FF;
    public const uint LightGrey = 0xd3d3d3FF;
    public const uint LightPink = 0xffb6c1FF;
    public const uint LightSalmon = 0xffa07aFF;
    public const uint LightSeaGreen = 0x20b2aaFF;
    public const uint LightSkyBlue = 0x87cefaFF;
    public const uint LightSlateGray = 0x778899FF;
    public const uint LightSlateGrey = 0x778899FF;
    public const uint LightSteelBlue = 0xb0c4deFF;
    public const uint LightYellow = 0xffffe0FF;
    public const uint LimeGreen = 0x32cd32FF;
    public const uint Linen = 0xfaf0e6FF;
    public const uint Magenta = 0xff00ffFF;
    public const uint MediumAquamarine = 0x66cdaaFF;
    public const uint MediumBlue = 0x0000cdFF;
    public const uint MediumOrchid = 0xba55d3FF;
    public const uint MediumPurple = 0x9370dbFF;
    public const uint MediumSeaGreen = 0x3cb371FF;
    public const uint MediumSlateBlue = 0x7b68eeFF;
    public const uint MediumSpringGreen = 0x00fa9aFF;
    public const uint MediumTurquoise = 0x48d1ccFF;
    public const uint MediumVioletRed = 0xc71585FF;
    public const uint MidnightBlue = 0x191970FF;
    public const uint MintCream = 0xf5fffaFF;
    public const uint MistyRose = 0xffe4e1FF;
    public const uint Moccasin = 0xffe4b5FF;
    public const uint NavajoWhite = 0xffdeadFF;
    public const uint OldLace = 0xfdf5e6FF;
    public const uint OliveDrab = 0x6b8e23FF;
    public const uint Orange = 0xffa500FF;
    public const uint OrangeRed = 0xff4500FF;
    public const uint Orchid = 0xda70d6FF;
    public const uint PaleGoldenRod = 0xeee8aaFF;
    public const uint PaleGreen = 0x98fb98FF;
    public const uint PaleTurquoise = 0xafeeeeFF;
    public const uint PaleVioletRed = 0xdb7093FF;
    public const uint PapayaWhip = 0xffefd5FF;
    public const uint PeachPuff = 0xffdab9FF;
    public const uint Peru = 0xcd853fFF;
    public const uint Pink = 0xffc0cbFF;
    public const uint Plum = 0xdda0ddFF;
    public const uint PowderBlue = 0xb0e0e6FF;
    public const uint RebeccaPurple = 0x663399FF;
    public const uint RosyBrown = 0xbc8f8fFF;
    public const uint RoyalBlue = 0x4169e1FF;
    public const uint SaddleBrown = 0x8b4513FF;
    public const uint Salmon = 0xfa8072FF;
    public const uint SandyBrown = 0xf4a460FF;
    public const uint SeaGreen = 0x2e8b57FF;
    public const uint Seashell = 0xfff5eeFF;
    public const uint Sienna = 0xa0522dFF;
    public const uint SkyBlue = 0x87ceebFF;
    public const uint SlateBlue = 0x6a5acdFF;
    public const uint SlateGray = 0x708090FF;
    public const uint SlateGrey = 0x708090FF;
    public const uint Snow = 0xfffafaFF;
    public const uint SpringGreen = 0x00ff7fFF;
    public const uint SteelBlue = 0x4682b4FF;
    public const uint Tan = 0xd2b48cFF;
    public const uint Thistle = 0xd8bfd8FF;
    public const uint Tomato = 0xff6347FF;
    public const uint Turquoise = 0x40e0d0FF;
    public const uint Violet = 0xee82eeFF;
    public const uint Wheat = 0xf5deb3FF;
    public const uint WhiteSmoke = 0xf5f5f5FF;
    public const uint YellowGreen = 0x9acd32FF;
}